// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQJ6517MA62pJW0l-AoENvhFeXN65jWNk',
    appId: '1:482510938256:web:18852e4209712b9abe3815',
    messagingSenderId: '482510938256',
    projectId: 'math-ai-90d85',
    authDomain: 'math-ai-90d85.firebaseapp.com',
    storageBucket: 'math-ai-90d85.firebasestorage.app',
    measurementId: 'G-THQCPPXY9T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7Os9I2L9gyzD99BH-YBaxZEySVtsGGyc',
    appId: '1:482510938256:android:5e73eb43404429fabe3815',
    messagingSenderId: '482510938256',
    projectId: 'math-ai-90d85',
    storageBucket: 'math-ai-90d85.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3Cer0v8PKG9-hQV2jJkfiJzfL7c6wlrc',
    appId: '1:482510938256:ios:be170147b3a3367abe3815',
    messagingSenderId: '482510938256',
    projectId: 'math-ai-90d85',
    storageBucket: 'math-ai-90d85.firebasestorage.app',
    iosBundleId: 'com.example.mathAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3Cer0v8PKG9-hQV2jJkfiJzfL7c6wlrc',
    appId: '1:482510938256:ios:be170147b3a3367abe3815',
    messagingSenderId: '482510938256',
    projectId: 'math-ai-90d85',
    storageBucket: 'math-ai-90d85.firebasestorage.app',
    iosBundleId: 'com.example.mathAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQJ6517MA62pJW0l-AoENvhFeXN65jWNk',
    appId: '1:482510938256:web:c79c15c123e74605be3815',
    messagingSenderId: '482510938256',
    projectId: 'math-ai-90d85',
    authDomain: 'math-ai-90d85.firebaseapp.com',
    storageBucket: 'math-ai-90d85.firebasestorage.app',
    measurementId: 'G-B93CEKNVV1',
  );
}
